watcher:
  zone:
    "example.jp":
      nameserver:
        - name: "foo"
          type: "A"
          ttl: 3600
          content: "192.168.0.254"
      record:
        - name: "bar"
          type: "A"
          ttl: 3600
          content: "192.168.0.253"
      dynamicGroup:
        - dynamicrecord:
          - name: "foo"
            type: "a"
            ttl: 10 
            content: "192.168.0.1"
            watchinterval: 5
            alive: 1
            notifytrigger:
            - changed
            - latestDown
            target:
            - name: t1
              protocol: icmp
              dest: 192.168.0.1
              retry: 3
              retrywait: 1
              timeout: 1
              tlsskipverify: true
            - name: t2
              protocol: tcpRegexp
              dest: 192.168.0.1:80
              regexp: "hogehoge2"
              ressize: 2000
              retry: 3
              retrywait: 1
              timeout: 2
              tcptls: true
              tlsskipverify: true
            - name: t3
              protocol: httpRegexp
              dest: 192.168.0.1:80
              regexp: "hogehoge3"
              ressize: 3000
              httpmethod: "GET"
              httpstatus: ["200"]
              retry: 3
              retrywait: 1
              timeout: 3
              tlsskipverify: true
            evalrule: "%(t1) && %(t2) && %(t3)"
          negativerecord:
          - name: "foo"
            type: "a"
            tl: 10
            content: "192.168.0.254"
notifier:
  mail:
  - hostport: smtp.example.com:25
    username: bob
    password: password
    to: alice@example.com
    from: bob@example.com
    authtype: plain
    usestarttls: true
    usetls: true
    tlsskipverify: true
    subject: "%(hostname) %(zone) %(name) %(content): old alive = %(oldAlive) -> new alive = %(newAlive)"
    body: "hostname: %(hostname)\nzone: %(zone)\nrecord: %(name) %(type) %(content)\n%(time) old alive = %(oldAlive) -> new alive = %(newAlive)\n%(detail)"
server:
  debug: true
  listen:
  - addrport: 0.0.0.0:28080
  username: hoge
  password: hoge
logger:
  loggers:
    "default":
      filter:
        structname: LogLevelFilter
        structsetters:
        - settername: SetLogLevel
          setterparams:
          - "8"
      formatter:
        structname: StandardFormatter
        structsetters:
        - settername: SetAppendNewLine
          setterparams:
          - "true"
        - settername: SetDateTimeLayout
          setterparams:
          - 2006-01-02 15:04:05 -0700 mst
        - settername: SetLayout
          setterparams:
          - '%(dateTime) [%(logLevel)] (%(pid)) %(programCounter) %(loggerName) %(shortFileName) %(lineNum) %(message)'
      handlers:
      - structname: ConsoleHandler
        structsetters:
        - settername: SetOutputType
          setterparams:
          - "1"
